
repos:
-   repo: https://github.com/asottile/reorder_python_imports
    rev: v1.5.0
    hooks:
    -   id: reorder-python-imports
- repo: https://github.com/ambv/black
  rev: stable
  hooks:
  - id: black
    language_version: python3.7
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v1.3.0
  hooks:
  - id: flake8
    language_version: python3.7
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.701
    hooks:
    -   id: mypy
        exclude: ^(docs/|example-plugin/|tests/fixtures)
